FROM node:17.6.0-alpine as base

WORKDIR /app
COPY ./package.json .
COPY ./package-lock.json .
COPY scripts/dev.sh ./scripts/dev.sh

RUN npm install && npm cache clean --force

# Copy source
COPY src ./src
COPY tsconfig.json .
COPY nodemon.json .
COPY openAPI ./openAPI

# Expose port 3000
EXPOSE 3000
CMD ["npm","run","start:dev"]
